"""initial schema

Revision ID: 12425079965b
Revises: 
Create Date: 2026-03-17 12:31:21.410658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12425079965b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=50), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('rtsp_url', sa.String(length=255), nullable=False),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('frame_rate', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_zones_zone_id'), ['zone_id'], unique=True)

    op.create_table('detection_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=50), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('behavior_flags', sa.JSON(), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_events_alert_triggered'), ['alert_triggered'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_events_zone_id'), ['zone_id'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['detection_events.event_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_zone_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))

    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('system_logs')
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_events_zone_id'))
        batch_op.drop_index(batch_op.f('ix_detection_events_detected_at'))
        batch_op.drop_index(batch_op.f('ix_detection_events_alert_triggered'))

    op.drop_table('detection_events')
    with op.batch_alter_table('camera_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_zones_zone_id'))

    op.drop_table('camera_zones')
    # ### end Alembic commands ###
