"""add bbox to detection events

Revision ID: 1d101530efdb
Revises: 12425079965b
Create Date: 2026-03-21 19:03:50.605968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d101530efdb'
down_revision = '12425079965b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bbox', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.drop_column('bbox')

    # ### end Alembic commands ###
