"""add alert detected_at index

Revision ID: abcb4ad65250
Revises: d11561c95587
Create Date: 2026-04-30 15:49:52.698744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abcb4ad65250'
down_revision = 'd11561c95587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_zones_is_active'))

    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.create_index('ix_detection_events_alert_detected_at', ['alert_triggered', 'detected_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_events_alert_detected_at')

    with op.batch_alter_table('camera_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_zones_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###
