"""add alert detected_at index

Revision ID: abcb4ad65250
Revises: d11561c95587
Create Date: 2026-04-30 15:49:52.698744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abcb4ad65250'
down_revision = 'd11561c95587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('alert_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_zone_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_zone_status_triggered_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('camera_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_zones_is_active'))

    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.create_index('ix_detection_events_alert_detected_at', ['alert_triggered', 'detected_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_events', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_events_alert_detected_at')

    with op.batch_alter_table('camera_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_zones_is_active'), ['is_active'], unique=False)

    op.create_table('alerts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('zone_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('triggered_at', mysql.DATETIME(), nullable=True),
    sa.Column('acknowledged_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', mysql.DATETIME(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('alerts_ibfk_2')),
    sa.ForeignKeyConstraint(['event_id'], ['detection_events.event_id'], name=op.f('alerts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_zone_status_triggered_at'), ['zone_id', 'status', 'triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_zone_id'), ['zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('alert_id'), ['alert_id'], unique=True)

    # ### end Alembic commands ###
