"""drop alert table

Revision ID: d11561c95587
Revises: e5f6a7b8c9d0
Create Date: 2026-04-30 15:17:36.371341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11561c95587'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_zones_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_triggered_at_desc_like'), ['triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###
